### PR TITLE
fix(types): alias path, type template and filename

### PR DESCRIPTION
**Pull request by adamdehaven**
1. Fix the `alias` to allow picking up any file in the directory: 

    ```typescript
    nuxt.options.alias = {
      ...nuxt.options.alias,
      '#open-fetch-schemas/*': join(nuxt.options.buildDir, 'types', moduleName, 'schemas', '*'),
    }
    ```
5. Properly export the types with a `*.d.ts` extension, using the `addTypeTemplate` method instead of `addTemplate`.

Attempting to fix the type resolution error reported [here](https://github.com/enkot/nuxt-open-fetch/issues/32#issuecomment-2181840773).

image

I need to build and test this locally in my project before I'm 100% sure it will fix the issue. If you're able to publish a prerelease version I can pull it in to verify for sure (or I can build my project locally Friday morning).

### CODE REVIEW

**Comment by adamdehaven** [comment]
I think it's getting closer, but still not perfect. My `layer` that imports the package has both of these `path` aliases in the generated `./.nuxt/tsconfig.json` file:
```ts
"#open-fetch-schemas": [
  "./types/open-fetch/schemas"
],
"#open-fetch-schemas/*": [
  "./types/open-fetch/schemas/*"
]
```

But my app that imports the layer above only resolves one of the paths (the wrong one) so the path to the actual schema types does not resolve:
```ts
"#open-fetch-schemas": [
  "./types/open-fetch/schemas"
]
```

**Comment by adamdehaven** [comment]
I pushed another fix to properly resolve the `paths` - I think it might be good to go (but I can verify again in the morning)

**Comment by enkot** [comment]
@adamdehaven Thank you for you contribution!

**Comment by adamdehaven** [comment]
> I can't really reproduce the problem with imports

Do you have type checking enabled in the Nuxt host app? 

```typescript
// nuxt.config.ts
typescript: {
  strict: true,
  typeCheck: true,
  includeWorkspace: true,
},
```

To be honest, I think just fixing the `alias` that is created would resolve my issue. I added the extension changes as I looked quickly and thought it was just exporting types. Let me test real quick with just updating the exported `alias`

**Comment by adamdehaven** [comment]
@enkot I updated the PR to only include the `alias` change

**Comment by enkot** [comment]
Screenshot 2024-06-21 at 19 35 32
Yes, `npx nuxi typecheck` passes.
I think it can be the problem in Nuxt itself, because it should automatically generate `#my-alias` and `#my-alias/*`.

Could you please share you project structure in terms of how the layers are registered, maybe some child layer also registers `nuxt-open-fetch` module?

**Comment by enkot** [comment]
@adamdehaven I have created a small repro and still can't reproduce the issue: https://stackblitz.com/edit/github-bxdf3a?file=layers%2Fportal%2Fapp.vue

**Comment by adamdehaven** [comment]
Something isn't correct with your reproduction; it's not even generating `.nuxt` directories to do the type checking

**Comment by enkot** [comment]
@adamdehaven You should run `npm i`  inside `/core` and `/portal` first, then inside `/portal` run `npm run dev` or `npx nuxi prepare`.

**Comment by adamdehaven** [comment]
Typechecking doesn't work in the reproduction even if I add `typescript` and `vue-tsc`

Would you mind trying explicitly adding the updated `alias` from this PR and testing?

I'm not sure if Nuxt is adding the one with the `/*` path, but regardless, that is what should be exported by the package [here](https://github.com/enkot/nuxt-open-fetch/blob/797c37405936c655c25870a9acea93e3c99b980e/src/module.ts#L101-L104), otherwise no child file of `.nuxt/types/open-fetch/schemas/*` will be able to be resolved.

I'm not sure if it's currently "lucky" that Nuxt is adding that additional `alias` for you, but it's definitely not working with my pnpm mono repository 😅

**Comment by enkot** [comment]
> ```js
> apps/
> └── portal/
>     ├── package.json
>     └── nuxt.config.ts // extends core layer
> layers/
> └── core/
>     ├── package.json // nuxt-open-fetch is a dependency here
>     └── nuxt.config.ts
> ```
> 
> Changing the alias to `#open-fetch-schemas/*` shouldn't cause problems, but should resolve my issue.

As I understand, you use some monorepo setup and this is not a complete project structure :)
This is what Nuxt generates in the repro I shared before (not monorepo, just 2 independent Nuxt projects):
```ts
      "#open-fetch-schemas": [
        "./types/open-fetch/schemas"
      ],
      "#open-fetch-schemas/*": [
        "./types/open-fetch/schemas/*"
      ],
```

I think it wouldn't be a good idea to possibly fix one specific problem and break the module for all other users. 
It would be great if you could create another issue with a complete repro (github repo or stackblitz), I'd be happy to help :)

**Comment by adamdehaven** [comment]
> fix one specific problem and break the module for all other users

To be honest I think the existing `alias` you're adding is already broken. If you aren't adding the explicit alias that is needed, but depending on Nuxt to "magically" add it:

> I think it can be the problem in Nuxt itself, because it should automatically generate `#my-alias` and `#my-alias/*`.

Where does Nuxt document that it is supposed to be creating this extra alias for you?

Here's a reproduction of the issue: https://github.com/adamdehaven/nuxt-monorepo-reproductions/tree/test/nuxt-open-fetch-types

## Steps to reproduce

1. Clone this repo.
2. Check out the `test/nuxt-open-fetch-types` branch.
3. Install dependencies from the root with `pnpm install`
4. From the root, run the `prepare` command recursively for each package: `pnpm -r prepare`
5. From the root, build the `app` that extends the `core` layer: `pnpm -F app build`
6. Inspect the generated `apps/app/.nuxt/tsconfig.json` and you will notice it only creates a single `alias` entry (should be around line `80`):

   ```typescript
    "#open-fetch-schemas": [
      "./types/open-fetch/schemas"
    ],
   ```

7. Inspect the `apps/app/.nuxt/open-fetch.ts` file and notice that TypeScript cannot find the module for the `#open-fetch-schemas/my-api` import on line `2`.

   typescript error

**Comment by adamdehaven** [comment]
I'm fine to just manually add the alias to my `nuxt.config.ts` in my `core` layer to resolve, but thought it would be more ideal if the alias was explicitly defined here at the source

```typescript
alias: {
  '#open-fetch-schemas/portal-api': fileURLToPath(new URL('./.nuxt/types/open-fetch/schemas/portal-api.ts', import.meta.url)),
}
```

**Comment by enkot** [comment]
It is weird why it behaves differently for build https://github.com/nuxt/nuxt/blob/main/packages/kit/src/template.ts#L244.
So I agree, let's be explicit in this case.  
Thank you for the PR :) 💚

**Comment by adamdehaven** [comment]
@enkot I can confirm this resolved the issue in my project 🎉  Thanks for the discussion ❤️

**Pull request merged**
